# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: timo.portfolio::lang.education.name

# Model Form Field configuration
form: $/timo/portfolio/models/education/fields.yaml

# Model Class name
modelClass: Timo\Portfolio\Models\Education

# Default redirect location
defaultRedirect: timo/portfolio/education

# Create page
create:
    title: backend::lang.form.create_title
    redirect: timo/portfolio/education/update/:id
    redirectClose: timo/portfolio/education

# Update page
update:
    title: backend::lang.form.update_title
    redirect: timo/portfolio/education
    redirectClose: timo/portfolio/education

# Preview page
preview:
    title: backend::lang.form.preview_title
