# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: timo.portfolio::lang.project.name

# Model Form Field configuration
form: $/timo/portfolio/models/project/fields.yaml

# Model Class name
modelClass: Timo\Portfolio\Models\Project

# Default redirect location
defaultRedirect: timo/portfolio/project

# Create page
create:
    title: backend::lang.form.create_title
    redirect: timo/portfolio/project/update/:id
    redirectClose: timo/portfolio/project

# Update page
update:
    title: backend::lang.form.update_title
    redirect: timo/portfolio/project
    redirectClose: timo/portfolio/project

# Preview page
preview:
    title: backend::lang.form.preview_title
