# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: timo.portfolio::lang.technology.name

# Model Form Field configuration
form: $/timo/portfolio/models/technology/fields.yaml

# Model Class name
modelClass: Timo\Portfolio\Models\Technology

# Default redirect location
defaultRedirect: timo/portfolio/technology

# Create page
create:
    title: backend::lang.form.create_title
    redirect: timo/portfolio/technology/update/:id
    redirectClose: timo/portfolio/technology

# Update page
update:
    title: backend::lang.form.update_title
    redirect: timo/portfolio/technology
    redirectClose: timo/portfolio/technology

# Preview page
preview:
    title: backend::lang.form.preview_title
